// <auto-generated />
using System;
using User.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace User.Persistence.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20250110015229_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.EventStore.Snapshot<User.Domain.Aggregates.User>", b =>
                {
                    b.Property<decimal>("Version")
                        .HasColumnType("decimal(20,0)");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Aggregate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp");

                    b.HasKey("Version", "AggregateId");

                    b.ToTable("UserSnapshots");
                });

            modelBuilder.Entity("Core.Domain.EventStore.StoreEvent<User.Domain.Aggregates.User>", b =>
                {
                    b.Property<decimal>("Version")
                        .HasColumnType("decimal(20,0)");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTimeOffset>("Timestamp")
                        .HasColumnType("timestamp");

                    b.HasKey("Version", "AggregateId");

                    b.ToTable("UserStoreEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
