// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using User.Persistence;

#nullable disable

namespace User.Persistence.Migrations
{
    [DbContext(typeof(UserDbContext))]
    [Migration("20260426024328_UpgradeToEFCore9")]
    partial class UpgradeToEFCore9
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("Users")
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Core.Domain.EventStore.Snapshot<User.Domain.Aggregates.User>", b =>
                {
                    b.Property<ulong>("Version")
                        .HasColumnType("bigint unsigned");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Aggregate")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Version", "AggregateId");

                    b.ToTable("UserSnapshots", "Users");
                });

            modelBuilder.Entity("Core.Domain.EventStore.StoreEvent<User.Domain.Aggregates.User>", b =>
                {
                    b.Property<ulong>("Version")
                        .HasColumnType("bigint unsigned");

                    b.Property<Guid>("AggregateId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Version", "AggregateId");

                    b.ToTable("UserStoreEvents", "Users");
                });
#pragma warning restore 612, 618
        }
    }
}
